### ISSUE TITLE
Constant Error Spam.

### ISSUE THREAD

**Issue by gotex007** [rljohn/pibuddy#11]
248x PIBuddy/priest.lua:381: attempt to index upvalue 'main' (a nil value)
[string "@PIBuddy/priest.lua"]:381: in function `UpdatePowerInfusionCooldown'
[string "@PIBuddy/events.lua"]:206: in function `OnCooldownUpdate'
[string "@PIBuddy/events.lua"]:226: in function <PIBuddy/events.lua:217>

Locals:
self = PIBuddyConfig {
 0 = <userdata>
 GetMacroText = <function> defined @PIBuddy/macros.lua:168
 CreatePiMeSoundWidgets = <function> defined @PIBuddy/config_panels.lua:910
 CreateWidgets = <function> defined @PIBuddy/config_panels.lua:6
 GetTalentNodeForSpell = <function> defined @PIBuddy/helper.lua:240
 UpdateDpsAlpha = <function> defined @PIBuddy/dps.lua:158
 InGroup = false
 DenyBuddyRequest = <function> defined @PIBuddy/messages.lua:402
 OnDpsCooldownRequest = <function> defined @PIBuddy/messages.lua:236
 SetPriestName = <function> defined @PIBuddy/priest.lua:117
 CreatePriestConfig = <function> defined @PIBuddy/config_panels.lua:1019
 OnPlayerFocusChanged = <function> defined @PIBuddy/config.lua:235
 ResetPriestInfo = <function> defined @PIBuddy/buddy.lua:36
 NotifyDpsInfoChanged = <function> defined @PIBuddy/messages.lua:130
 Lock = <function> defined @PIBuddy/config.lua:368
 SetMainFrameCheckDpsVisibility = <function> defined @PIBuddy/dps.lua:79
 CreateRaidPriestBuddy = <function> defined @PIBuddy/config_panels.lua:638
 ResetDpsInfo = <function> defined @PIBuddy/buddy.lua:42
 titles = <table> {
 }
 ResetInfo = <function> defined @PIBuddy/buddy.lua:9
 SetMainFrameFocusMeButton = <function> defined @PIBuddy/main.lua:208
 IsOneWayEnabled = <function> defined @PIBuddy/config.lua:312
 ConfirmRequestBuddy = <function> defined @PIBuddy/messages.lua:369
 UpdatePiMeRequest = <function> defined @PIBuddy/priest.lua:273
 InRaid = false
 PlayerLevel = 70
 OnPiMeRequest = <function> defined @PIBuddy/messages.lua:300
 RefreshPIMacros = <function> defined @PIBuddy/macros.lua:229
 OnLogout = <function> defined @PIBuddy/config.lua:302
 SyncInfo = <function> defined @PIBuddy/buddy.lua:425
 UpdateBuddyStatusUi = <function> defined @PIBuddy/config_panels.lua:350
 ShouldResetFrames = false
 ResetAndResyncPriest = <function> defined @PIBuddy/buddy.lua:88
 SetDpsBuddy = <function> defined @PIBuddy/buddy.lua:166
 OnPIBuddyRequest = <function> defined @PIBuddy/messages.lua:365
 OnGainDpsCooldown = <function> defined @PIBuddy/dps.lua:179
 SetMainFrameNoPIWarningVisible = <function> defined @PIBuddy/main.lua:372
 SetMainFrameNoFocusWarningVisible = <function> defined @PIBuddy/main.lua:363
 NotifyPICooldownChanged = <function> defined @PIBuddy/messages.lua:217
 ExportMacrosRaid = false
 NotifyDpsCooldownChanged = <function> defined @PIBuddy/messages.lua:263
 CreatePriestWidgets = <function> defined @PIBuddy/priest.lua:17
 NotifyDpsActiveChanged = <function> defined @PIBuddy/messages.lua:276
 CreatePartyDpsBuddy = <function> defined @PIBuddy/config_panels.lua:398
 UpdateDeadBuddy = <function> defined @PIBuddy/buddy.lua:511
 Initialized = false
 CreatePartyPriestBuddy = <function> defined @PIBuddy/config_panels.lua:473
 OnTalentsChanged = <function> defined @PIBuddy/config.lua:199
 SetMainFrameTitleVisible = <function> defined @PIBuddy/main.lua:190
 CreatePIMacroPanel = <function> defined @PIBuddy/macros.lua:34
 OnDpsCooldownReply = <function> defined @PIBuddy/messages.lua:253
 ReplaceTooltip = <function> defined @PIBuddy/helper.lua:122
 SendPriestInfoRequest = <function> defined @PIBuddy/messages.lua:148
 SetMainFrameBackgroundVisible = <function> defined @PIBuddy/main.lua:180
 OnResize = <function> defined @PIBuddy/main.lua:159
 name = "PI Buddy"
 CreatePa

**Comment by rljohn** [comment]
Thanks, I'll fix this tonight.
