### ISSUE TITLE
SpellName localization

### ISSUE THREAD

**Issue by ssiruguet** [rljohn/pibuddy#16]
PIBuddy Macro not working in french because "Power Infusion" is not a valid spellName in french is "Infusion de Puissance"

i think we can get the good spellname by calling the GetSpellInfo function like this 
>
> local spellName = GetSpellInfo(10060); 
>

then use this spellName variable in the macro generator
>
>text = text .. string.format('\n/cast [@%s,help,nodead] '..spellName , opt.env.DpsBuddy)
>

**Comment by rljohn** [comment]
Good shout. I'll make an update soon to use the newer C_Spell.GetSpellName
for this.

**Comment by ssiruguet** [comment]
thx for update, 

i got a new error in priest.lua on line 335 attempt to call global 'GetSpellCooldown' (a nil value)
start, duration, enabled = GetSpellCooldown(opt.PriestInfo.spell_id);

**Comment by rljohn** [comment]
Ok, I'll check it out.

**Comment by rljohn** [comment]
Should be fixed in 1.32
